name: vf CI

on: [push, pull_request]

jobs:
  static-font-ci-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    name: SpaceG vf *.ttf font build CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python v${{ matrix.python-version }} environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python build dependency cache lookup
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          # Check for requirements file cache hit
          key: ${{ runner.os }}-pip-${{ hashFiles('${{ steps.config.outputs.dependpath }}') }}
      - name: Install Python build dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-wheel: "true"
          update-setuptools: "true"
      - name: Install ttfautohint (Ubuntu package manager)
        run: sudo apt-get install ttfautohint
      - name: Build fonts
        run: cd sources && ./build.sh && cd ..
      - name: Font Bakery CI tests
        uses: f-actions/font-bakery@v1
        with:
          version: "latest"
          subcmd: "check-googlefonts"
          args: "-C --loglevel WARN"
          path: "fonts/ttf/*.ttf"
